import requests
import time
import json

API_BASE = "http://localhost:8000"

def test_feedback_safety():
    print("--- 1. Testing High Risk Secondary Confirmation ---")
    # We need a transaction with risk > 70. 
    # Since we can't easily force simulation to hit 70 without history, 
    # we'll assume the API is running and fetch transactions to find one, 
    # or just try a feedback with dummy ID that doesn't exist to see validation logic if we could, 
    # but the API checks txn_lookup.
    
    # Better: Use a mock txn in the lookup if we could, but we can't easily.
    # Let's wait for some transactions to be generated by the background simulation.
    print("Waiting for transactions...")
    time.sleep(10)
    txns = requests.get(f"{API_BASE}/transactions").json()
    
    target_txn = None
    for t in txns:
        if t.get('risk_score', 0) > 70:
            target_txn = t
            break
            
    if target_txn:
        print(f"Found High Risk TXN: {target_txn['transaction_id']} (Score: {target_txn['risk_score']})")
        # Try without confirmation
        res = requests.post(f"{API_BASE}/feedback", json={
            "transaction_id": target_txn['transaction_id'],
            "feedback": "LEGITIMATE"
        })
        print(f"No Confirm Response: {res.json().get('status')}")
        
        # Try with confirmation
        res = requests.post(f"{API_BASE}/feedback", json={
            "transaction_id": target_txn['transaction_id'],
            "feedback": "LEGITIMATE",
            "pin_confirmed": True,
            "beneficiary_confirmed": True
        })
        print(f"Confirmed Response: {res.json().get('message')}")
    else:
        print("No high-risk transactions found in recent feed. Try increasing simulation risk.")

    print("\n--- 2. Testing Session Risk Block (Simulated) ---")
    # This requires session risk to accumulate. In a live test, we'd need multiple high risk txns.
    # In this script, we just note that the logic is in api_main.py:180 and user_profiler.py:65.

if __name__ == "__main__":
    test_feedback_safety()
